### ISSUE TITLE
The value of SHA256_BLOCK_SIZE seems not correct

### ISSUE THREAD

**Issue by sgetzpeng** [B-Con/crypto-algorithms#27]
https://github.com/B-Con/crypto-algorithms/blob/cfbde48414baacf51fc7c74f275190881f037d32/sha256.h#L16
Hi @B-Con,
I understand the definitions doesn't affect the implementation because it isn't referred.
Just a gentle reminder that the block size should  be 64, right?  32 should be digest size.

/Sgetz

**Comment by sijanec** [comment]
So you're implying that SHA256 yields a 64 byte hash? As far as I know, the hash is indeed 32 bytes. From the name "SHA**256**" it's visible that the hash is 256 bits long and that unsigned chars are used as bytes (8 bits), we can calculate that the hash is 256/8 (32) bytes long.

Maybe you're referring to the size of bytes if the hash is converted to a hexadecimal string and as one hexadecimal character represents 4 bits but takes 8 bits of space, the resulting "block" would be two times larger. This implementation does not store hashes as hexadecimal strings.

**Comment by sgetzpeng** [comment]
@sijanec 
Thanks for your reply. However, According to the SHA standard, the output value size and the block size might be different. For example, according to https://en.wikipedia.org/wiki/Secure_Hash_Algorithms, SHA-224 and SHA-256's output size is 28 and 32 respectively, but both of the block size are 64 bytes(512-bit).
Any comments?

/Sgetz

**Comment by sijanec** [comment]
Oh, sorry about that. You're right. I thougt this specified the output
value size, because in the sha256_test.c it's used for the size of the
output array if I understand correctly.

If you're still interested, I ended up using the sha-2 C library that is
also in public domain and is here on Github.



Pardon me, this message was composed on a mobile device. Please excuse any
typos.

**Comment by sgetzpeng** [comment]
@sijanec 
Never mind. The library is very good and I appreciate your release. Moreover, It would not confuse anyone if you replace  `SHA256_BLOCK_SIZE` with `SHA256_OUTPUT_SIZE`.
Just my 2 cents.:smile:
/Sgetz
